### ISSUE TITLE
Skip / optional hacks

### ISSUE THREAD

**Issue by Allistakn** [MattMills/stellarstellaris#1]
First of all thanks for that smooth piece and the workshop item with the same name.

Is there a simple way to select which hack to apply or to skip ? Some of them maybe be too much for some, specially the 3d ship rendering part.

**Comment by MattMills** [comment]
There isn't right now, I've been meaning to add some command line options, for ship graphics you can comment this line out https://github.com/MattMills/stellarstellaris/blob/master/main.c#L561 and they should stick around.

**Comment by Allistakn** [comment]
I can confirm that commenting the line keep the 3d ships around and that the rest work as usual. Btw I'm still astonished by the changes it brings, and also that you have to go the hard way.

From a user pov (sorry but this is really really above me) I think the parts where people could want some abilities to choose are mainly  : 

- The 3d ships on the map
- What makes the mouse selection goes visually unnoticed (as in, if you go with the mouse on a sector/system you do not have visual feedback on the fact that it is indeed selected or hoovered). 

It seems, to me at least, that the rest is less sensitive.

**Comment by MattMills** [comment]
Hrm I don't use sectors so I've never noticed the second part, I'll have to look at that.

**Comment by Allistakn** [comment]
I can confirm that commenting the line keep the 3d ships around and that the rest work as usual. Btw I'm still astonished by the changes it brings, and also that you have to go the hard way.

From a user pov (sorry but this is really really above me) I think the parts where people could want some abilities to choose are mainly  : 

- The 3d ships on the map
- What makes the mouse selection goes visually unnoticed (as in, if you go with the mouse on a sector you do not have visual feedback on the fact that it is indeed selected or hoovered). 

It seems, to me at least, that the rest is less sensitive.

**Comment by MattMills** [comment]
I'll leave this open until I add the command line options and look into the visual issue.

**Comment by MattMills** [comment]
```
Usage/Help:
        ./stellarstellaris -p stellaris_pid [options]

Options [SUBJECT TO CHANGE]:

        -a Turn on ::KillObject changes (in dev) [default = off]
        -b Turn off CFleetView::Update changes [default = on]
        -c Turn off CMapIconManager::UpdateGalacticObjectIcon changes [default = on]
        -d Turn off CPlanetView::Update changes [default = on]
        -e Turn off CPdxParticleObject::RenderBuckets changes [default = on]
        -f Turn off CShipGraphics::Update changes [default = on]
        -g Disable CGui::PerFrameUpdate (game breaking) [default = enabled]
        -h Disable CGui::HandelInput (input breaking) [default = enabled]
        -i Disable COutliner::InternalUpdate (?? breaking) [default = enabled]
        -j Turn on in development rendering thread code (currently broken)
```

options added in e6c95d7a33784764517684769d95918cdd2df1bf
